// @generated by tools/gen_currency_table.py from data/iso4217/codes-all.csv.
// DO NOT EDIT BY HAND. See data/iso4217/README.md for provenance and verification.
// One currency per line; rustfmt skips this file (see `mod table` in currency.rs).

use super::{Currency, CurrencyInfo, CurrencyStatus};

static AED_INFO: CurrencyInfo = CurrencyInfo::new("AED", 784, 2, "UAE Dirham", CurrencyStatus::Circulating);
static AFN_INFO: CurrencyInfo = CurrencyInfo::new("AFN", 971, 2, "Afghani", CurrencyStatus::Circulating);
static ALL_INFO: CurrencyInfo = CurrencyInfo::new("ALL", 8, 2, "Lek", CurrencyStatus::Circulating);
static AMD_INFO: CurrencyInfo = CurrencyInfo::new("AMD", 51, 2, "Armenian Dram", CurrencyStatus::Circulating);
static ANG_INFO: CurrencyInfo = CurrencyInfo::new("ANG", 532, 2, "Netherlands Antillean Guilder", CurrencyStatus::Withdrawn { year: 2025, month: 3 });
static AOA_INFO: CurrencyInfo = CurrencyInfo::new("AOA", 973, 2, "Kwanza", CurrencyStatus::Circulating);
static ARS_INFO: CurrencyInfo = CurrencyInfo::new("ARS", 32, 2, "Argentine Peso", CurrencyStatus::Circulating);
static AUD_INFO: CurrencyInfo = CurrencyInfo::new("AUD", 36, 2, "Australian Dollar", CurrencyStatus::Circulating);
static AWG_INFO: CurrencyInfo = CurrencyInfo::new("AWG", 533, 2, "Aruban Florin", CurrencyStatus::Circulating);
static AZN_INFO: CurrencyInfo = CurrencyInfo::new("AZN", 944, 2, "Azerbaijan Manat", CurrencyStatus::Circulating);
static BAM_INFO: CurrencyInfo = CurrencyInfo::new("BAM", 977, 2, "Convertible Mark", CurrencyStatus::Circulating);
static BBD_INFO: CurrencyInfo = CurrencyInfo::new("BBD", 52, 2, "Barbados Dollar", CurrencyStatus::Circulating);
static BDT_INFO: CurrencyInfo = CurrencyInfo::new("BDT", 50, 2, "Taka", CurrencyStatus::Circulating);
static BGN_INFO: CurrencyInfo = CurrencyInfo::new("BGN", 975, 2, "Bulgarian Lev", CurrencyStatus::Withdrawn { year: 2026, month: 1 });
static BHD_INFO: CurrencyInfo = CurrencyInfo::new("BHD", 48, 3, "Bahraini Dinar", CurrencyStatus::Circulating);
static BIF_INFO: CurrencyInfo = CurrencyInfo::new("BIF", 108, 0, "Burundi Franc", CurrencyStatus::Circulating);
static BMD_INFO: CurrencyInfo = CurrencyInfo::new("BMD", 60, 2, "Bermudian Dollar", CurrencyStatus::Circulating);
static BND_INFO: CurrencyInfo = CurrencyInfo::new("BND", 96, 2, "Brunei Dollar", CurrencyStatus::Circulating);
static BOB_INFO: CurrencyInfo = CurrencyInfo::new("BOB", 68, 2, "Boliviano", CurrencyStatus::Circulating);
static BRL_INFO: CurrencyInfo = CurrencyInfo::new("BRL", 986, 2, "Brazilian Real", CurrencyStatus::Circulating);
static BSD_INFO: CurrencyInfo = CurrencyInfo::new("BSD", 44, 2, "Bahamian Dollar", CurrencyStatus::Circulating);
static BTN_INFO: CurrencyInfo = CurrencyInfo::new("BTN", 64, 2, "Ngultrum", CurrencyStatus::Circulating);
static BWP_INFO: CurrencyInfo = CurrencyInfo::new("BWP", 72, 2, "Pula", CurrencyStatus::Circulating);
static BYN_INFO: CurrencyInfo = CurrencyInfo::new("BYN", 933, 2, "Belarusian Ruble", CurrencyStatus::Circulating);
static BZD_INFO: CurrencyInfo = CurrencyInfo::new("BZD", 84, 2, "Belize Dollar", CurrencyStatus::Circulating);
static CAD_INFO: CurrencyInfo = CurrencyInfo::new("CAD", 124, 2, "Canadian Dollar", CurrencyStatus::Circulating);
static CDF_INFO: CurrencyInfo = CurrencyInfo::new("CDF", 976, 2, "Congolese Franc", CurrencyStatus::Circulating);
static CHF_INFO: CurrencyInfo = CurrencyInfo::new("CHF", 756, 2, "Swiss Franc", CurrencyStatus::Circulating);
static CLP_INFO: CurrencyInfo = CurrencyInfo::new("CLP", 152, 0, "Chilean Peso", CurrencyStatus::Circulating);
static CNY_INFO: CurrencyInfo = CurrencyInfo::new("CNY", 156, 2, "Yuan Renminbi", CurrencyStatus::Circulating);
static COP_INFO: CurrencyInfo = CurrencyInfo::new("COP", 170, 2, "Colombian Peso", CurrencyStatus::Circulating);
static CRC_INFO: CurrencyInfo = CurrencyInfo::new("CRC", 188, 2, "Costa Rican Colon", CurrencyStatus::Circulating);
static CUC_INFO: CurrencyInfo = CurrencyInfo::new("CUC", 931, 2, "Peso Convertible", CurrencyStatus::Withdrawn { year: 2021, month: 6 });
static CUP_INFO: CurrencyInfo = CurrencyInfo::new("CUP", 192, 2, "Cuban Peso", CurrencyStatus::Circulating);
static CVE_INFO: CurrencyInfo = CurrencyInfo::new("CVE", 132, 2, "Cabo Verde Escudo", CurrencyStatus::Circulating);
static CZK_INFO: CurrencyInfo = CurrencyInfo::new("CZK", 203, 2, "Czech Koruna", CurrencyStatus::Circulating);
static DJF_INFO: CurrencyInfo = CurrencyInfo::new("DJF", 262, 0, "Djibouti Franc", CurrencyStatus::Circulating);
static DKK_INFO: CurrencyInfo = CurrencyInfo::new("DKK", 208, 2, "Danish Krone", CurrencyStatus::Circulating);
static DOP_INFO: CurrencyInfo = CurrencyInfo::new("DOP", 214, 2, "Dominican Peso", CurrencyStatus::Circulating);
static DZD_INFO: CurrencyInfo = CurrencyInfo::new("DZD", 12, 2, "Algerian Dinar", CurrencyStatus::Circulating);
static EGP_INFO: CurrencyInfo = CurrencyInfo::new("EGP", 818, 2, "Egyptian Pound", CurrencyStatus::Circulating);
static ERN_INFO: CurrencyInfo = CurrencyInfo::new("ERN", 232, 2, "Nakfa", CurrencyStatus::Circulating);
static ETB_INFO: CurrencyInfo = CurrencyInfo::new("ETB", 230, 2, "Ethiopian Birr", CurrencyStatus::Circulating);
static EUR_INFO: CurrencyInfo = CurrencyInfo::new("EUR", 978, 2, "Euro", CurrencyStatus::Circulating);
static FJD_INFO: CurrencyInfo = CurrencyInfo::new("FJD", 242, 2, "Fiji Dollar", CurrencyStatus::Circulating);
static FKP_INFO: CurrencyInfo = CurrencyInfo::new("FKP", 238, 2, "Falkland Islands Pound", CurrencyStatus::Circulating);
static GBP_INFO: CurrencyInfo = CurrencyInfo::new("GBP", 826, 2, "Pound Sterling", CurrencyStatus::Circulating);
static GEL_INFO: CurrencyInfo = CurrencyInfo::new("GEL", 981, 2, "Lari", CurrencyStatus::Circulating);
static GHS_INFO: CurrencyInfo = CurrencyInfo::new("GHS", 936, 2, "Ghana Cedi", CurrencyStatus::Circulating);
static GIP_INFO: CurrencyInfo = CurrencyInfo::new("GIP", 292, 2, "Gibraltar Pound", CurrencyStatus::Circulating);
static GMD_INFO: CurrencyInfo = CurrencyInfo::new("GMD", 270, 2, "Dalasi", CurrencyStatus::Circulating);
static GNF_INFO: CurrencyInfo = CurrencyInfo::new("GNF", 324, 0, "Guinean Franc", CurrencyStatus::Circulating);
static GTQ_INFO: CurrencyInfo = CurrencyInfo::new("GTQ", 320, 2, "Quetzal", CurrencyStatus::Circulating);
static GYD_INFO: CurrencyInfo = CurrencyInfo::new("GYD", 328, 2, "Guyana Dollar", CurrencyStatus::Circulating);
static HKD_INFO: CurrencyInfo = CurrencyInfo::new("HKD", 344, 2, "Hong Kong Dollar", CurrencyStatus::Circulating);
static HNL_INFO: CurrencyInfo = CurrencyInfo::new("HNL", 340, 2, "Lempira", CurrencyStatus::Circulating);
static HRK_INFO: CurrencyInfo = CurrencyInfo::new("HRK", 191, 2, "Kuna", CurrencyStatus::Withdrawn { year: 2023, month: 1 });
static HTG_INFO: CurrencyInfo = CurrencyInfo::new("HTG", 332, 2, "Gourde", CurrencyStatus::Circulating);
static HUF_INFO: CurrencyInfo = CurrencyInfo::new("HUF", 348, 2, "Forint", CurrencyStatus::Circulating);
static IDR_INFO: CurrencyInfo = CurrencyInfo::new("IDR", 360, 2, "Rupiah", CurrencyStatus::Circulating);
static ILS_INFO: CurrencyInfo = CurrencyInfo::new("ILS", 376, 2, "New Israeli Sheqel", CurrencyStatus::Circulating);
static INR_INFO: CurrencyInfo = CurrencyInfo::new("INR", 356, 2, "Indian Rupee", CurrencyStatus::Circulating);
static IQD_INFO: CurrencyInfo = CurrencyInfo::new("IQD", 368, 3, "Iraqi Dinar", CurrencyStatus::Circulating);
static IRR_INFO: CurrencyInfo = CurrencyInfo::new("IRR", 364, 2, "Iranian Rial", CurrencyStatus::Circulating);
static ISK_INFO: CurrencyInfo = CurrencyInfo::new("ISK", 352, 0, "Iceland Krona", CurrencyStatus::Circulating);
static JMD_INFO: CurrencyInfo = CurrencyInfo::new("JMD", 388, 2, "Jamaican Dollar", CurrencyStatus::Circulating);
static JOD_INFO: CurrencyInfo = CurrencyInfo::new("JOD", 400, 3, "Jordanian Dinar", CurrencyStatus::Circulating);
static JPY_INFO: CurrencyInfo = CurrencyInfo::new("JPY", 392, 0, "Yen", CurrencyStatus::Circulating);
static KES_INFO: CurrencyInfo = CurrencyInfo::new("KES", 404, 2, "Kenyan Shilling", CurrencyStatus::Circulating);
static KGS_INFO: CurrencyInfo = CurrencyInfo::new("KGS", 417, 2, "Som", CurrencyStatus::Circulating);
static KHR_INFO: CurrencyInfo = CurrencyInfo::new("KHR", 116, 2, "Riel", CurrencyStatus::Circulating);
static KMF_INFO: CurrencyInfo = CurrencyInfo::new("KMF", 174, 0, "Comorian Franc", CurrencyStatus::Circulating);
static KPW_INFO: CurrencyInfo = CurrencyInfo::new("KPW", 408, 2, "North Korean Won", CurrencyStatus::Circulating);
static KRW_INFO: CurrencyInfo = CurrencyInfo::new("KRW", 410, 0, "Won", CurrencyStatus::Circulating);
static KWD_INFO: CurrencyInfo = CurrencyInfo::new("KWD", 414, 3, "Kuwaiti Dinar", CurrencyStatus::Circulating);
static KYD_INFO: CurrencyInfo = CurrencyInfo::new("KYD", 136, 2, "Cayman Islands Dollar", CurrencyStatus::Circulating);
static KZT_INFO: CurrencyInfo = CurrencyInfo::new("KZT", 398, 2, "Tenge", CurrencyStatus::Circulating);
static LAK_INFO: CurrencyInfo = CurrencyInfo::new("LAK", 418, 2, "Lao Kip", CurrencyStatus::Circulating);
static LBP_INFO: CurrencyInfo = CurrencyInfo::new("LBP", 422, 2, "Lebanese Pound", CurrencyStatus::Circulating);
static LKR_INFO: CurrencyInfo = CurrencyInfo::new("LKR", 144, 2, "Sri Lanka Rupee", CurrencyStatus::Circulating);
static LRD_INFO: CurrencyInfo = CurrencyInfo::new("LRD", 430, 2, "Liberian Dollar", CurrencyStatus::Circulating);
static LSL_INFO: CurrencyInfo = CurrencyInfo::new("LSL", 426, 2, "Loti", CurrencyStatus::Circulating);
static LYD_INFO: CurrencyInfo = CurrencyInfo::new("LYD", 434, 3, "Libyan Dinar", CurrencyStatus::Circulating);
static MAD_INFO: CurrencyInfo = CurrencyInfo::new("MAD", 504, 2, "Moroccan Dirham", CurrencyStatus::Circulating);
static MDL_INFO: CurrencyInfo = CurrencyInfo::new("MDL", 498, 2, "Moldovan Leu", CurrencyStatus::Circulating);
static MGA_INFO: CurrencyInfo = CurrencyInfo::new("MGA", 969, 2, "Malagasy Ariary", CurrencyStatus::Circulating);
static MKD_INFO: CurrencyInfo = CurrencyInfo::new("MKD", 807, 2, "Denar", CurrencyStatus::Circulating);
static MMK_INFO: CurrencyInfo = CurrencyInfo::new("MMK", 104, 2, "Kyat", CurrencyStatus::Circulating);
static MNT_INFO: CurrencyInfo = CurrencyInfo::new("MNT", 496, 2, "Tugrik", CurrencyStatus::Circulating);
static MOP_INFO: CurrencyInfo = CurrencyInfo::new("MOP", 446, 2, "Pataca", CurrencyStatus::Circulating);
static MRU_INFO: CurrencyInfo = CurrencyInfo::new("MRU", 929, 2, "Ouguiya", CurrencyStatus::Circulating);
static MUR_INFO: CurrencyInfo = CurrencyInfo::new("MUR", 480, 2, "Mauritius Rupee", CurrencyStatus::Circulating);
static MVR_INFO: CurrencyInfo = CurrencyInfo::new("MVR", 462, 2, "Rufiyaa", CurrencyStatus::Circulating);
static MWK_INFO: CurrencyInfo = CurrencyInfo::new("MWK", 454, 2, "Malawi Kwacha", CurrencyStatus::Circulating);
static MXN_INFO: CurrencyInfo = CurrencyInfo::new("MXN", 484, 2, "Mexican Peso", CurrencyStatus::Circulating);
static MYR_INFO: CurrencyInfo = CurrencyInfo::new("MYR", 458, 2, "Malaysian Ringgit", CurrencyStatus::Circulating);
static MZN_INFO: CurrencyInfo = CurrencyInfo::new("MZN", 943, 2, "Mozambique Metical", CurrencyStatus::Circulating);
static NAD_INFO: CurrencyInfo = CurrencyInfo::new("NAD", 516, 2, "Namibia Dollar", CurrencyStatus::Circulating);
static NGN_INFO: CurrencyInfo = CurrencyInfo::new("NGN", 566, 2, "Naira", CurrencyStatus::Circulating);
static NIO_INFO: CurrencyInfo = CurrencyInfo::new("NIO", 558, 2, "Cordoba Oro", CurrencyStatus::Circulating);
static NOK_INFO: CurrencyInfo = CurrencyInfo::new("NOK", 578, 2, "Norwegian Krone", CurrencyStatus::Circulating);
static NPR_INFO: CurrencyInfo = CurrencyInfo::new("NPR", 524, 2, "Nepalese Rupee", CurrencyStatus::Circulating);
static NZD_INFO: CurrencyInfo = CurrencyInfo::new("NZD", 554, 2, "New Zealand Dollar", CurrencyStatus::Circulating);
static OMR_INFO: CurrencyInfo = CurrencyInfo::new("OMR", 512, 3, "Rial Omani", CurrencyStatus::Circulating);
static PAB_INFO: CurrencyInfo = CurrencyInfo::new("PAB", 590, 2, "Balboa", CurrencyStatus::Circulating);
static PEN_INFO: CurrencyInfo = CurrencyInfo::new("PEN", 604, 2, "Sol", CurrencyStatus::Circulating);
static PGK_INFO: CurrencyInfo = CurrencyInfo::new("PGK", 598, 2, "Kina", CurrencyStatus::Circulating);
static PHP_INFO: CurrencyInfo = CurrencyInfo::new("PHP", 608, 2, "Philippine Peso", CurrencyStatus::Circulating);
static PKR_INFO: CurrencyInfo = CurrencyInfo::new("PKR", 586, 2, "Pakistan Rupee", CurrencyStatus::Circulating);
static PLN_INFO: CurrencyInfo = CurrencyInfo::new("PLN", 985, 2, "Zloty", CurrencyStatus::Circulating);
static PYG_INFO: CurrencyInfo = CurrencyInfo::new("PYG", 600, 0, "Guarani", CurrencyStatus::Circulating);
static QAR_INFO: CurrencyInfo = CurrencyInfo::new("QAR", 634, 2, "Qatari Rial", CurrencyStatus::Circulating);
static RON_INFO: CurrencyInfo = CurrencyInfo::new("RON", 946, 2, "Romanian Leu", CurrencyStatus::Circulating);
static RSD_INFO: CurrencyInfo = CurrencyInfo::new("RSD", 941, 2, "Serbian Dinar", CurrencyStatus::Circulating);
static RUB_INFO: CurrencyInfo = CurrencyInfo::new("RUB", 643, 2, "Russian Ruble", CurrencyStatus::Circulating);
static RWF_INFO: CurrencyInfo = CurrencyInfo::new("RWF", 646, 0, "Rwanda Franc", CurrencyStatus::Circulating);
static SAR_INFO: CurrencyInfo = CurrencyInfo::new("SAR", 682, 2, "Saudi Riyal", CurrencyStatus::Circulating);
static SBD_INFO: CurrencyInfo = CurrencyInfo::new("SBD", 90, 2, "Solomon Islands Dollar", CurrencyStatus::Circulating);
static SCR_INFO: CurrencyInfo = CurrencyInfo::new("SCR", 690, 2, "Seychelles Rupee", CurrencyStatus::Circulating);
static SDG_INFO: CurrencyInfo = CurrencyInfo::new("SDG", 938, 2, "Sudanese Pound", CurrencyStatus::Circulating);
static SEK_INFO: CurrencyInfo = CurrencyInfo::new("SEK", 752, 2, "Swedish Krona", CurrencyStatus::Circulating);
static SGD_INFO: CurrencyInfo = CurrencyInfo::new("SGD", 702, 2, "Singapore Dollar", CurrencyStatus::Circulating);
static SHP_INFO: CurrencyInfo = CurrencyInfo::new("SHP", 654, 2, "Saint Helena Pound", CurrencyStatus::Circulating);
static SLE_INFO: CurrencyInfo = CurrencyInfo::new("SLE", 925, 2, "Leone", CurrencyStatus::Circulating);
static SLL_INFO: CurrencyInfo = CurrencyInfo::new("SLL", 694, 2, "Leone", CurrencyStatus::Withdrawn { year: 2023, month: 12 });
static SOS_INFO: CurrencyInfo = CurrencyInfo::new("SOS", 706, 2, "Somali Shilling", CurrencyStatus::Circulating);
static SRD_INFO: CurrencyInfo = CurrencyInfo::new("SRD", 968, 2, "Surinam Dollar", CurrencyStatus::Circulating);
static SSP_INFO: CurrencyInfo = CurrencyInfo::new("SSP", 728, 2, "South Sudanese Pound", CurrencyStatus::Circulating);
static STN_INFO: CurrencyInfo = CurrencyInfo::new("STN", 930, 2, "Dobra", CurrencyStatus::Circulating);
static SVC_INFO: CurrencyInfo = CurrencyInfo::new("SVC", 222, 2, "El Salvador Colon", CurrencyStatus::Circulating);
static SYP_INFO: CurrencyInfo = CurrencyInfo::new("SYP", 760, 2, "Syrian Pound", CurrencyStatus::Circulating);
static SZL_INFO: CurrencyInfo = CurrencyInfo::new("SZL", 748, 2, "Lilangeni", CurrencyStatus::Circulating);
static THB_INFO: CurrencyInfo = CurrencyInfo::new("THB", 764, 2, "Baht", CurrencyStatus::Circulating);
static TJS_INFO: CurrencyInfo = CurrencyInfo::new("TJS", 972, 2, "Somoni", CurrencyStatus::Circulating);
static TMT_INFO: CurrencyInfo = CurrencyInfo::new("TMT", 934, 2, "Turkmenistan New Manat", CurrencyStatus::Circulating);
static TND_INFO: CurrencyInfo = CurrencyInfo::new("TND", 788, 3, "Tunisian Dinar", CurrencyStatus::Circulating);
static TOP_INFO: CurrencyInfo = CurrencyInfo::new("TOP", 776, 2, "Pa’anga", CurrencyStatus::Circulating);
static TRY_INFO: CurrencyInfo = CurrencyInfo::new("TRY", 949, 2, "Turkish Lira", CurrencyStatus::Circulating);
static TTD_INFO: CurrencyInfo = CurrencyInfo::new("TTD", 780, 2, "Trinidad and Tobago Dollar", CurrencyStatus::Circulating);
static TWD_INFO: CurrencyInfo = CurrencyInfo::new("TWD", 901, 2, "New Taiwan Dollar", CurrencyStatus::Circulating);
static TZS_INFO: CurrencyInfo = CurrencyInfo::new("TZS", 834, 2, "Tanzanian Shilling", CurrencyStatus::Circulating);
static UAH_INFO: CurrencyInfo = CurrencyInfo::new("UAH", 980, 2, "Hryvnia", CurrencyStatus::Circulating);
static UGX_INFO: CurrencyInfo = CurrencyInfo::new("UGX", 800, 0, "Uganda Shilling", CurrencyStatus::Circulating);
static USD_INFO: CurrencyInfo = CurrencyInfo::new("USD", 840, 2, "US Dollar", CurrencyStatus::Circulating);
static UYU_INFO: CurrencyInfo = CurrencyInfo::new("UYU", 858, 2, "Peso Uruguayo", CurrencyStatus::Circulating);
static UZS_INFO: CurrencyInfo = CurrencyInfo::new("UZS", 860, 2, "Uzbekistan Sum", CurrencyStatus::Circulating);
static VED_INFO: CurrencyInfo = CurrencyInfo::new("VED", 926, 2, "Bolívar Soberano", CurrencyStatus::Circulating);
static VES_INFO: CurrencyInfo = CurrencyInfo::new("VES", 928, 2, "Bolívar Soberano", CurrencyStatus::Circulating);
static VND_INFO: CurrencyInfo = CurrencyInfo::new("VND", 704, 0, "Dong", CurrencyStatus::Circulating);
static VUV_INFO: CurrencyInfo = CurrencyInfo::new("VUV", 548, 0, "Vatu", CurrencyStatus::Circulating);
static WST_INFO: CurrencyInfo = CurrencyInfo::new("WST", 882, 2, "Tala", CurrencyStatus::Circulating);
static XAF_INFO: CurrencyInfo = CurrencyInfo::new("XAF", 950, 0, "CFA Franc BEAC", CurrencyStatus::Circulating);
static XCD_INFO: CurrencyInfo = CurrencyInfo::new("XCD", 951, 2, "East Caribbean Dollar", CurrencyStatus::Circulating);
static XCG_INFO: CurrencyInfo = CurrencyInfo::new("XCG", 532, 2, "Caribbean Guilder", CurrencyStatus::Circulating);
static XOF_INFO: CurrencyInfo = CurrencyInfo::new("XOF", 952, 0, "CFA Franc BCEAO", CurrencyStatus::Circulating);
static XPF_INFO: CurrencyInfo = CurrencyInfo::new("XPF", 953, 0, "CFP Franc", CurrencyStatus::Circulating);
static YER_INFO: CurrencyInfo = CurrencyInfo::new("YER", 886, 2, "Yemeni Rial", CurrencyStatus::Circulating);
static ZAR_INFO: CurrencyInfo = CurrencyInfo::new("ZAR", 710, 2, "Rand", CurrencyStatus::Circulating);
static ZMW_INFO: CurrencyInfo = CurrencyInfo::new("ZMW", 967, 2, "Zambian Kwacha", CurrencyStatus::Circulating);
static ZWG_INFO: CurrencyInfo = CurrencyInfo::new("ZWG", 924, 2, "Zimbabwe Gold", CurrencyStatus::Circulating);
static ZWL_INFO: CurrencyInfo = CurrencyInfo::new("ZWL", 932, 2, "Zimbabwe Dollar", CurrencyStatus::Withdrawn { year: 2024, month: 9 });

/// Every currency in the table, sorted by alphabetic code.
pub(super) static TABLE: [&CurrencyInfo; 161] = [
    &AED_INFO,
    &AFN_INFO,
    &ALL_INFO,
    &AMD_INFO,
    &ANG_INFO,
    &AOA_INFO,
    &ARS_INFO,
    &AUD_INFO,
    &AWG_INFO,
    &AZN_INFO,
    &BAM_INFO,
    &BBD_INFO,
    &BDT_INFO,
    &BGN_INFO,
    &BHD_INFO,
    &BIF_INFO,
    &BMD_INFO,
    &BND_INFO,
    &BOB_INFO,
    &BRL_INFO,
    &BSD_INFO,
    &BTN_INFO,
    &BWP_INFO,
    &BYN_INFO,
    &BZD_INFO,
    &CAD_INFO,
    &CDF_INFO,
    &CHF_INFO,
    &CLP_INFO,
    &CNY_INFO,
    &COP_INFO,
    &CRC_INFO,
    &CUC_INFO,
    &CUP_INFO,
    &CVE_INFO,
    &CZK_INFO,
    &DJF_INFO,
    &DKK_INFO,
    &DOP_INFO,
    &DZD_INFO,
    &EGP_INFO,
    &ERN_INFO,
    &ETB_INFO,
    &EUR_INFO,
    &FJD_INFO,
    &FKP_INFO,
    &GBP_INFO,
    &GEL_INFO,
    &GHS_INFO,
    &GIP_INFO,
    &GMD_INFO,
    &GNF_INFO,
    &GTQ_INFO,
    &GYD_INFO,
    &HKD_INFO,
    &HNL_INFO,
    &HRK_INFO,
    &HTG_INFO,
    &HUF_INFO,
    &IDR_INFO,
    &ILS_INFO,
    &INR_INFO,
    &IQD_INFO,
    &IRR_INFO,
    &ISK_INFO,
    &JMD_INFO,
    &JOD_INFO,
    &JPY_INFO,
    &KES_INFO,
    &KGS_INFO,
    &KHR_INFO,
    &KMF_INFO,
    &KPW_INFO,
    &KRW_INFO,
    &KWD_INFO,
    &KYD_INFO,
    &KZT_INFO,
    &LAK_INFO,
    &LBP_INFO,
    &LKR_INFO,
    &LRD_INFO,
    &LSL_INFO,
    &LYD_INFO,
    &MAD_INFO,
    &MDL_INFO,
    &MGA_INFO,
    &MKD_INFO,
    &MMK_INFO,
    &MNT_INFO,
    &MOP_INFO,
    &MRU_INFO,
    &MUR_INFO,
    &MVR_INFO,
    &MWK_INFO,
    &MXN_INFO,
    &MYR_INFO,
    &MZN_INFO,
    &NAD_INFO,
    &NGN_INFO,
    &NIO_INFO,
    &NOK_INFO,
    &NPR_INFO,
    &NZD_INFO,
    &OMR_INFO,
    &PAB_INFO,
    &PEN_INFO,
    &PGK_INFO,
    &PHP_INFO,
    &PKR_INFO,
    &PLN_INFO,
    &PYG_INFO,
    &QAR_INFO,
    &RON_INFO,
    &RSD_INFO,
    &RUB_INFO,
    &RWF_INFO,
    &SAR_INFO,
    &SBD_INFO,
    &SCR_INFO,
    &SDG_INFO,
    &SEK_INFO,
    &SGD_INFO,
    &SHP_INFO,
    &SLE_INFO,
    &SLL_INFO,
    &SOS_INFO,
    &SRD_INFO,
    &SSP_INFO,
    &STN_INFO,
    &SVC_INFO,
    &SYP_INFO,
    &SZL_INFO,
    &THB_INFO,
    &TJS_INFO,
    &TMT_INFO,
    &TND_INFO,
    &TOP_INFO,
    &TRY_INFO,
    &TTD_INFO,
    &TWD_INFO,
    &TZS_INFO,
    &UAH_INFO,
    &UGX_INFO,
    &USD_INFO,
    &UYU_INFO,
    &UZS_INFO,
    &VED_INFO,
    &VES_INFO,
    &VND_INFO,
    &VUV_INFO,
    &WST_INFO,
    &XAF_INFO,
    &XCD_INFO,
    &XCG_INFO,
    &XOF_INFO,
    &XPF_INFO,
    &YER_INFO,
    &ZAR_INFO,
    &ZMW_INFO,
    &ZWG_INFO,
    &ZWL_INFO,
];

impl Currency {
    /// UAE Dirham (`AED`, ISO 4217 numeric 784, 2 minor units).
    pub const AED: Currency = Currency(&AED_INFO);
    /// Afghani (`AFN`, ISO 4217 numeric 971, 2 minor units).
    pub const AFN: Currency = Currency(&AFN_INFO);
    /// Lek (`ALL`, ISO 4217 numeric 008, 2 minor units).
    pub const ALL: Currency = Currency(&ALL_INFO);
    /// Armenian Dram (`AMD`, ISO 4217 numeric 051, 2 minor units).
    pub const AMD: Currency = Currency(&AMD_INFO);
    /// Netherlands Antillean Guilder (`ANG`, ISO 4217 numeric 532, 2 minor units). Withdrawn 2025-03.
    pub const ANG: Currency = Currency(&ANG_INFO);
    /// Kwanza (`AOA`, ISO 4217 numeric 973, 2 minor units).
    pub const AOA: Currency = Currency(&AOA_INFO);
    /// Argentine Peso (`ARS`, ISO 4217 numeric 032, 2 minor units).
    pub const ARS: Currency = Currency(&ARS_INFO);
    /// Australian Dollar (`AUD`, ISO 4217 numeric 036, 2 minor units).
    pub const AUD: Currency = Currency(&AUD_INFO);
    /// Aruban Florin (`AWG`, ISO 4217 numeric 533, 2 minor units).
    pub const AWG: Currency = Currency(&AWG_INFO);
    /// Azerbaijan Manat (`AZN`, ISO 4217 numeric 944, 2 minor units).
    pub const AZN: Currency = Currency(&AZN_INFO);
    /// Convertible Mark (`BAM`, ISO 4217 numeric 977, 2 minor units).
    pub const BAM: Currency = Currency(&BAM_INFO);
    /// Barbados Dollar (`BBD`, ISO 4217 numeric 052, 2 minor units).
    pub const BBD: Currency = Currency(&BBD_INFO);
    /// Taka (`BDT`, ISO 4217 numeric 050, 2 minor units).
    pub const BDT: Currency = Currency(&BDT_INFO);
    /// Bulgarian Lev (`BGN`, ISO 4217 numeric 975, 2 minor units). Withdrawn 2026-01.
    pub const BGN: Currency = Currency(&BGN_INFO);
    /// Bahraini Dinar (`BHD`, ISO 4217 numeric 048, 3 minor units).
    pub const BHD: Currency = Currency(&BHD_INFO);
    /// Burundi Franc (`BIF`, ISO 4217 numeric 108, 0 minor units).
    pub const BIF: Currency = Currency(&BIF_INFO);
    /// Bermudian Dollar (`BMD`, ISO 4217 numeric 060, 2 minor units).
    pub const BMD: Currency = Currency(&BMD_INFO);
    /// Brunei Dollar (`BND`, ISO 4217 numeric 096, 2 minor units).
    pub const BND: Currency = Currency(&BND_INFO);
    /// Boliviano (`BOB`, ISO 4217 numeric 068, 2 minor units).
    pub const BOB: Currency = Currency(&BOB_INFO);
    /// Brazilian Real (`BRL`, ISO 4217 numeric 986, 2 minor units).
    pub const BRL: Currency = Currency(&BRL_INFO);
    /// Bahamian Dollar (`BSD`, ISO 4217 numeric 044, 2 minor units).
    pub const BSD: Currency = Currency(&BSD_INFO);
    /// Ngultrum (`BTN`, ISO 4217 numeric 064, 2 minor units).
    pub const BTN: Currency = Currency(&BTN_INFO);
    /// Pula (`BWP`, ISO 4217 numeric 072, 2 minor units).
    pub const BWP: Currency = Currency(&BWP_INFO);
    /// Belarusian Ruble (`BYN`, ISO 4217 numeric 933, 2 minor units).
    pub const BYN: Currency = Currency(&BYN_INFO);
    /// Belize Dollar (`BZD`, ISO 4217 numeric 084, 2 minor units).
    pub const BZD: Currency = Currency(&BZD_INFO);
    /// Canadian Dollar (`CAD`, ISO 4217 numeric 124, 2 minor units).
    pub const CAD: Currency = Currency(&CAD_INFO);
    /// Congolese Franc (`CDF`, ISO 4217 numeric 976, 2 minor units).
    pub const CDF: Currency = Currency(&CDF_INFO);
    /// Swiss Franc (`CHF`, ISO 4217 numeric 756, 2 minor units).
    pub const CHF: Currency = Currency(&CHF_INFO);
    /// Chilean Peso (`CLP`, ISO 4217 numeric 152, 0 minor units).
    pub const CLP: Currency = Currency(&CLP_INFO);
    /// Yuan Renminbi (`CNY`, ISO 4217 numeric 156, 2 minor units).
    pub const CNY: Currency = Currency(&CNY_INFO);
    /// Colombian Peso (`COP`, ISO 4217 numeric 170, 2 minor units).
    pub const COP: Currency = Currency(&COP_INFO);
    /// Costa Rican Colon (`CRC`, ISO 4217 numeric 188, 2 minor units).
    pub const CRC: Currency = Currency(&CRC_INFO);
    /// Peso Convertible (`CUC`, ISO 4217 numeric 931, 2 minor units). Withdrawn 2021-06.
    pub const CUC: Currency = Currency(&CUC_INFO);
    /// Cuban Peso (`CUP`, ISO 4217 numeric 192, 2 minor units).
    pub const CUP: Currency = Currency(&CUP_INFO);
    /// Cabo Verde Escudo (`CVE`, ISO 4217 numeric 132, 2 minor units).
    pub const CVE: Currency = Currency(&CVE_INFO);
    /// Czech Koruna (`CZK`, ISO 4217 numeric 203, 2 minor units).
    pub const CZK: Currency = Currency(&CZK_INFO);
    /// Djibouti Franc (`DJF`, ISO 4217 numeric 262, 0 minor units).
    pub const DJF: Currency = Currency(&DJF_INFO);
    /// Danish Krone (`DKK`, ISO 4217 numeric 208, 2 minor units).
    pub const DKK: Currency = Currency(&DKK_INFO);
    /// Dominican Peso (`DOP`, ISO 4217 numeric 214, 2 minor units).
    pub const DOP: Currency = Currency(&DOP_INFO);
    /// Algerian Dinar (`DZD`, ISO 4217 numeric 012, 2 minor units).
    pub const DZD: Currency = Currency(&DZD_INFO);
    /// Egyptian Pound (`EGP`, ISO 4217 numeric 818, 2 minor units).
    pub const EGP: Currency = Currency(&EGP_INFO);
    /// Nakfa (`ERN`, ISO 4217 numeric 232, 2 minor units).
    pub const ERN: Currency = Currency(&ERN_INFO);
    /// Ethiopian Birr (`ETB`, ISO 4217 numeric 230, 2 minor units).
    pub const ETB: Currency = Currency(&ETB_INFO);
    /// Euro (`EUR`, ISO 4217 numeric 978, 2 minor units).
    pub const EUR: Currency = Currency(&EUR_INFO);
    /// Fiji Dollar (`FJD`, ISO 4217 numeric 242, 2 minor units).
    pub const FJD: Currency = Currency(&FJD_INFO);
    /// Falkland Islands Pound (`FKP`, ISO 4217 numeric 238, 2 minor units).
    pub const FKP: Currency = Currency(&FKP_INFO);
    /// Pound Sterling (`GBP`, ISO 4217 numeric 826, 2 minor units).
    pub const GBP: Currency = Currency(&GBP_INFO);
    /// Lari (`GEL`, ISO 4217 numeric 981, 2 minor units).
    pub const GEL: Currency = Currency(&GEL_INFO);
    /// Ghana Cedi (`GHS`, ISO 4217 numeric 936, 2 minor units).
    pub const GHS: Currency = Currency(&GHS_INFO);
    /// Gibraltar Pound (`GIP`, ISO 4217 numeric 292, 2 minor units).
    pub const GIP: Currency = Currency(&GIP_INFO);
    /// Dalasi (`GMD`, ISO 4217 numeric 270, 2 minor units).
    pub const GMD: Currency = Currency(&GMD_INFO);
    /// Guinean Franc (`GNF`, ISO 4217 numeric 324, 0 minor units).
    pub const GNF: Currency = Currency(&GNF_INFO);
    /// Quetzal (`GTQ`, ISO 4217 numeric 320, 2 minor units).
    pub const GTQ: Currency = Currency(&GTQ_INFO);
    /// Guyana Dollar (`GYD`, ISO 4217 numeric 328, 2 minor units).
    pub const GYD: Currency = Currency(&GYD_INFO);
    /// Hong Kong Dollar (`HKD`, ISO 4217 numeric 344, 2 minor units).
    pub const HKD: Currency = Currency(&HKD_INFO);
    /// Lempira (`HNL`, ISO 4217 numeric 340, 2 minor units).
    pub const HNL: Currency = Currency(&HNL_INFO);
    /// Kuna (`HRK`, ISO 4217 numeric 191, 2 minor units). Withdrawn 2023-01.
    pub const HRK: Currency = Currency(&HRK_INFO);
    /// Gourde (`HTG`, ISO 4217 numeric 332, 2 minor units).
    pub const HTG: Currency = Currency(&HTG_INFO);
    /// Forint (`HUF`, ISO 4217 numeric 348, 2 minor units).
    pub const HUF: Currency = Currency(&HUF_INFO);
    /// Rupiah (`IDR`, ISO 4217 numeric 360, 2 minor units).
    pub const IDR: Currency = Currency(&IDR_INFO);
    /// New Israeli Sheqel (`ILS`, ISO 4217 numeric 376, 2 minor units).
    pub const ILS: Currency = Currency(&ILS_INFO);
    /// Indian Rupee (`INR`, ISO 4217 numeric 356, 2 minor units).
    pub const INR: Currency = Currency(&INR_INFO);
    /// Iraqi Dinar (`IQD`, ISO 4217 numeric 368, 3 minor units).
    pub const IQD: Currency = Currency(&IQD_INFO);
    /// Iranian Rial (`IRR`, ISO 4217 numeric 364, 2 minor units).
    pub const IRR: Currency = Currency(&IRR_INFO);
    /// Iceland Krona (`ISK`, ISO 4217 numeric 352, 0 minor units).
    pub const ISK: Currency = Currency(&ISK_INFO);
    /// Jamaican Dollar (`JMD`, ISO 4217 numeric 388, 2 minor units).
    pub const JMD: Currency = Currency(&JMD_INFO);
    /// Jordanian Dinar (`JOD`, ISO 4217 numeric 400, 3 minor units).
    pub const JOD: Currency = Currency(&JOD_INFO);
    /// Yen (`JPY`, ISO 4217 numeric 392, 0 minor units).
    pub const JPY: Currency = Currency(&JPY_INFO);
    /// Kenyan Shilling (`KES`, ISO 4217 numeric 404, 2 minor units).
    pub const KES: Currency = Currency(&KES_INFO);
    /// Som (`KGS`, ISO 4217 numeric 417, 2 minor units).
    pub const KGS: Currency = Currency(&KGS_INFO);
    /// Riel (`KHR`, ISO 4217 numeric 116, 2 minor units).
    pub const KHR: Currency = Currency(&KHR_INFO);
    /// Comorian Franc (`KMF`, ISO 4217 numeric 174, 0 minor units).
    pub const KMF: Currency = Currency(&KMF_INFO);
    /// North Korean Won (`KPW`, ISO 4217 numeric 408, 2 minor units).
    pub const KPW: Currency = Currency(&KPW_INFO);
    /// Won (`KRW`, ISO 4217 numeric 410, 0 minor units).
    pub const KRW: Currency = Currency(&KRW_INFO);
    /// Kuwaiti Dinar (`KWD`, ISO 4217 numeric 414, 3 minor units).
    pub const KWD: Currency = Currency(&KWD_INFO);
    /// Cayman Islands Dollar (`KYD`, ISO 4217 numeric 136, 2 minor units).
    pub const KYD: Currency = Currency(&KYD_INFO);
    /// Tenge (`KZT`, ISO 4217 numeric 398, 2 minor units).
    pub const KZT: Currency = Currency(&KZT_INFO);
    /// Lao Kip (`LAK`, ISO 4217 numeric 418, 2 minor units).
    pub const LAK: Currency = Currency(&LAK_INFO);
    /// Lebanese Pound (`LBP`, ISO 4217 numeric 422, 2 minor units).
    pub const LBP: Currency = Currency(&LBP_INFO);
    /// Sri Lanka Rupee (`LKR`, ISO 4217 numeric 144, 2 minor units).
    pub const LKR: Currency = Currency(&LKR_INFO);
    /// Liberian Dollar (`LRD`, ISO 4217 numeric 430, 2 minor units).
    pub const LRD: Currency = Currency(&LRD_INFO);
    /// Loti (`LSL`, ISO 4217 numeric 426, 2 minor units).
    pub const LSL: Currency = Currency(&LSL_INFO);
    /// Libyan Dinar (`LYD`, ISO 4217 numeric 434, 3 minor units).
    pub const LYD: Currency = Currency(&LYD_INFO);
    /// Moroccan Dirham (`MAD`, ISO 4217 numeric 504, 2 minor units).
    pub const MAD: Currency = Currency(&MAD_INFO);
    /// Moldovan Leu (`MDL`, ISO 4217 numeric 498, 2 minor units).
    pub const MDL: Currency = Currency(&MDL_INFO);
    /// Malagasy Ariary (`MGA`, ISO 4217 numeric 969, 2 minor units).
    pub const MGA: Currency = Currency(&MGA_INFO);
    /// Denar (`MKD`, ISO 4217 numeric 807, 2 minor units).
    pub const MKD: Currency = Currency(&MKD_INFO);
    /// Kyat (`MMK`, ISO 4217 numeric 104, 2 minor units).
    pub const MMK: Currency = Currency(&MMK_INFO);
    /// Tugrik (`MNT`, ISO 4217 numeric 496, 2 minor units).
    pub const MNT: Currency = Currency(&MNT_INFO);
    /// Pataca (`MOP`, ISO 4217 numeric 446, 2 minor units).
    pub const MOP: Currency = Currency(&MOP_INFO);
    /// Ouguiya (`MRU`, ISO 4217 numeric 929, 2 minor units).
    pub const MRU: Currency = Currency(&MRU_INFO);
    /// Mauritius Rupee (`MUR`, ISO 4217 numeric 480, 2 minor units).
    pub const MUR: Currency = Currency(&MUR_INFO);
    /// Rufiyaa (`MVR`, ISO 4217 numeric 462, 2 minor units).
    pub const MVR: Currency = Currency(&MVR_INFO);
    /// Malawi Kwacha (`MWK`, ISO 4217 numeric 454, 2 minor units).
    pub const MWK: Currency = Currency(&MWK_INFO);
    /// Mexican Peso (`MXN`, ISO 4217 numeric 484, 2 minor units).
    pub const MXN: Currency = Currency(&MXN_INFO);
    /// Malaysian Ringgit (`MYR`, ISO 4217 numeric 458, 2 minor units).
    pub const MYR: Currency = Currency(&MYR_INFO);
    /// Mozambique Metical (`MZN`, ISO 4217 numeric 943, 2 minor units).
    pub const MZN: Currency = Currency(&MZN_INFO);
    /// Namibia Dollar (`NAD`, ISO 4217 numeric 516, 2 minor units).
    pub const NAD: Currency = Currency(&NAD_INFO);
    /// Naira (`NGN`, ISO 4217 numeric 566, 2 minor units).
    pub const NGN: Currency = Currency(&NGN_INFO);
    /// Cordoba Oro (`NIO`, ISO 4217 numeric 558, 2 minor units).
    pub const NIO: Currency = Currency(&NIO_INFO);
    /// Norwegian Krone (`NOK`, ISO 4217 numeric 578, 2 minor units).
    pub const NOK: Currency = Currency(&NOK_INFO);
    /// Nepalese Rupee (`NPR`, ISO 4217 numeric 524, 2 minor units).
    pub const NPR: Currency = Currency(&NPR_INFO);
    /// New Zealand Dollar (`NZD`, ISO 4217 numeric 554, 2 minor units).
    pub const NZD: Currency = Currency(&NZD_INFO);
    /// Rial Omani (`OMR`, ISO 4217 numeric 512, 3 minor units).
    pub const OMR: Currency = Currency(&OMR_INFO);
    /// Balboa (`PAB`, ISO 4217 numeric 590, 2 minor units).
    pub const PAB: Currency = Currency(&PAB_INFO);
    /// Sol (`PEN`, ISO 4217 numeric 604, 2 minor units).
    pub const PEN: Currency = Currency(&PEN_INFO);
    /// Kina (`PGK`, ISO 4217 numeric 598, 2 minor units).
    pub const PGK: Currency = Currency(&PGK_INFO);
    /// Philippine Peso (`PHP`, ISO 4217 numeric 608, 2 minor units).
    pub const PHP: Currency = Currency(&PHP_INFO);
    /// Pakistan Rupee (`PKR`, ISO 4217 numeric 586, 2 minor units).
    pub const PKR: Currency = Currency(&PKR_INFO);
    /// Zloty (`PLN`, ISO 4217 numeric 985, 2 minor units).
    pub const PLN: Currency = Currency(&PLN_INFO);
    /// Guarani (`PYG`, ISO 4217 numeric 600, 0 minor units).
    pub const PYG: Currency = Currency(&PYG_INFO);
    /// Qatari Rial (`QAR`, ISO 4217 numeric 634, 2 minor units).
    pub const QAR: Currency = Currency(&QAR_INFO);
    /// Romanian Leu (`RON`, ISO 4217 numeric 946, 2 minor units).
    pub const RON: Currency = Currency(&RON_INFO);
    /// Serbian Dinar (`RSD`, ISO 4217 numeric 941, 2 minor units).
    pub const RSD: Currency = Currency(&RSD_INFO);
    /// Russian Ruble (`RUB`, ISO 4217 numeric 643, 2 minor units).
    pub const RUB: Currency = Currency(&RUB_INFO);
    /// Rwanda Franc (`RWF`, ISO 4217 numeric 646, 0 minor units).
    pub const RWF: Currency = Currency(&RWF_INFO);
    /// Saudi Riyal (`SAR`, ISO 4217 numeric 682, 2 minor units).
    pub const SAR: Currency = Currency(&SAR_INFO);
    /// Solomon Islands Dollar (`SBD`, ISO 4217 numeric 090, 2 minor units).
    pub const SBD: Currency = Currency(&SBD_INFO);
    /// Seychelles Rupee (`SCR`, ISO 4217 numeric 690, 2 minor units).
    pub const SCR: Currency = Currency(&SCR_INFO);
    /// Sudanese Pound (`SDG`, ISO 4217 numeric 938, 2 minor units).
    pub const SDG: Currency = Currency(&SDG_INFO);
    /// Swedish Krona (`SEK`, ISO 4217 numeric 752, 2 minor units).
    pub const SEK: Currency = Currency(&SEK_INFO);
    /// Singapore Dollar (`SGD`, ISO 4217 numeric 702, 2 minor units).
    pub const SGD: Currency = Currency(&SGD_INFO);
    /// Saint Helena Pound (`SHP`, ISO 4217 numeric 654, 2 minor units).
    pub const SHP: Currency = Currency(&SHP_INFO);
    /// Leone (`SLE`, ISO 4217 numeric 925, 2 minor units).
    pub const SLE: Currency = Currency(&SLE_INFO);
    /// Leone (`SLL`, ISO 4217 numeric 694, 2 minor units). Withdrawn 2023-12.
    pub const SLL: Currency = Currency(&SLL_INFO);
    /// Somali Shilling (`SOS`, ISO 4217 numeric 706, 2 minor units).
    pub const SOS: Currency = Currency(&SOS_INFO);
    /// Surinam Dollar (`SRD`, ISO 4217 numeric 968, 2 minor units).
    pub const SRD: Currency = Currency(&SRD_INFO);
    /// South Sudanese Pound (`SSP`, ISO 4217 numeric 728, 2 minor units).
    pub const SSP: Currency = Currency(&SSP_INFO);
    /// Dobra (`STN`, ISO 4217 numeric 930, 2 minor units).
    pub const STN: Currency = Currency(&STN_INFO);
    /// El Salvador Colon (`SVC`, ISO 4217 numeric 222, 2 minor units).
    pub const SVC: Currency = Currency(&SVC_INFO);
    /// Syrian Pound (`SYP`, ISO 4217 numeric 760, 2 minor units).
    pub const SYP: Currency = Currency(&SYP_INFO);
    /// Lilangeni (`SZL`, ISO 4217 numeric 748, 2 minor units).
    pub const SZL: Currency = Currency(&SZL_INFO);
    /// Baht (`THB`, ISO 4217 numeric 764, 2 minor units).
    pub const THB: Currency = Currency(&THB_INFO);
    /// Somoni (`TJS`, ISO 4217 numeric 972, 2 minor units).
    pub const TJS: Currency = Currency(&TJS_INFO);
    /// Turkmenistan New Manat (`TMT`, ISO 4217 numeric 934, 2 minor units).
    pub const TMT: Currency = Currency(&TMT_INFO);
    /// Tunisian Dinar (`TND`, ISO 4217 numeric 788, 3 minor units).
    pub const TND: Currency = Currency(&TND_INFO);
    /// Pa’anga (`TOP`, ISO 4217 numeric 776, 2 minor units).
    pub const TOP: Currency = Currency(&TOP_INFO);
    /// Turkish Lira (`TRY`, ISO 4217 numeric 949, 2 minor units).
    pub const TRY: Currency = Currency(&TRY_INFO);
    /// Trinidad and Tobago Dollar (`TTD`, ISO 4217 numeric 780, 2 minor units).
    pub const TTD: Currency = Currency(&TTD_INFO);
    /// New Taiwan Dollar (`TWD`, ISO 4217 numeric 901, 2 minor units).
    pub const TWD: Currency = Currency(&TWD_INFO);
    /// Tanzanian Shilling (`TZS`, ISO 4217 numeric 834, 2 minor units).
    pub const TZS: Currency = Currency(&TZS_INFO);
    /// Hryvnia (`UAH`, ISO 4217 numeric 980, 2 minor units).
    pub const UAH: Currency = Currency(&UAH_INFO);
    /// Uganda Shilling (`UGX`, ISO 4217 numeric 800, 0 minor units).
    pub const UGX: Currency = Currency(&UGX_INFO);
    /// US Dollar (`USD`, ISO 4217 numeric 840, 2 minor units).
    pub const USD: Currency = Currency(&USD_INFO);
    /// Peso Uruguayo (`UYU`, ISO 4217 numeric 858, 2 minor units).
    pub const UYU: Currency = Currency(&UYU_INFO);
    /// Uzbekistan Sum (`UZS`, ISO 4217 numeric 860, 2 minor units).
    pub const UZS: Currency = Currency(&UZS_INFO);
    /// Bolívar Soberano (`VED`, ISO 4217 numeric 926, 2 minor units).
    pub const VED: Currency = Currency(&VED_INFO);
    /// Bolívar Soberano (`VES`, ISO 4217 numeric 928, 2 minor units).
    pub const VES: Currency = Currency(&VES_INFO);
    /// Dong (`VND`, ISO 4217 numeric 704, 0 minor units).
    pub const VND: Currency = Currency(&VND_INFO);
    /// Vatu (`VUV`, ISO 4217 numeric 548, 0 minor units).
    pub const VUV: Currency = Currency(&VUV_INFO);
    /// Tala (`WST`, ISO 4217 numeric 882, 2 minor units).
    pub const WST: Currency = Currency(&WST_INFO);
    /// CFA Franc BEAC (`XAF`, ISO 4217 numeric 950, 0 minor units).
    pub const XAF: Currency = Currency(&XAF_INFO);
    /// East Caribbean Dollar (`XCD`, ISO 4217 numeric 951, 2 minor units).
    pub const XCD: Currency = Currency(&XCD_INFO);
    /// Caribbean Guilder (`XCG`, ISO 4217 numeric 532, 2 minor units).
    pub const XCG: Currency = Currency(&XCG_INFO);
    /// CFA Franc BCEAO (`XOF`, ISO 4217 numeric 952, 0 minor units).
    pub const XOF: Currency = Currency(&XOF_INFO);
    /// CFP Franc (`XPF`, ISO 4217 numeric 953, 0 minor units).
    pub const XPF: Currency = Currency(&XPF_INFO);
    /// Yemeni Rial (`YER`, ISO 4217 numeric 886, 2 minor units).
    pub const YER: Currency = Currency(&YER_INFO);
    /// Rand (`ZAR`, ISO 4217 numeric 710, 2 minor units).
    pub const ZAR: Currency = Currency(&ZAR_INFO);
    /// Zambian Kwacha (`ZMW`, ISO 4217 numeric 967, 2 minor units).
    pub const ZMW: Currency = Currency(&ZMW_INFO);
    /// Zimbabwe Gold (`ZWG`, ISO 4217 numeric 924, 2 minor units).
    pub const ZWG: Currency = Currency(&ZWG_INFO);
    /// Zimbabwe Dollar (`ZWL`, ISO 4217 numeric 932, 2 minor units). Withdrawn 2024-09.
    pub const ZWL: Currency = Currency(&ZWL_INFO);
}
