#!/usr/bin/env python3
"""Generate src/locale/table.rs from the CLDR snapshot in data/cldr/.

Run from anywhere:  python3 core/crates/keel-types/tools/gen_locale_table.py

For each locale Keel formats for, the snapshot holds CLDR's `numbers.json` and `currencies.json`.
The script takes from them the decimal, grouping and minus symbols, and each currency's symbol,
and checks that everything else CLDR says about how an amount or a quantity looks is what
`Locale` implements:

- the currency pattern `¤#,##0.00`, and `¤ #,##0.00` (with a no-break space) beside a letter;
- currency spacing, on both sides of the symbol: a no-break space between a digit and a symbol
  whose nearest character isn't a symbol or a separator;
- the decimal pattern `#,##0.###`, grouping by thousands from four digits, and Latin digits;
- no separators of currency amounts' own, and no currency with a separator or pattern of its own.

Anything else stops it with an error, so that a CLDR update can change only the symbols and
separators the table holds, which CI's check of the table shows, and never how `Locale` arranges
them. See data/cldr/README.md.
"""

from __future__ import annotations

import json
import sys
import unicodedata
from pathlib import Path

CRATE = Path(__file__).resolve().parent.parent
DATA = CRATE / "data" / "cldr"
OUT_PATH = CRATE / "src" / "locale" / "table.rs"

# The locales Keel formats for: the BCP 47 tag, the CLDR locale whose data it uses, and the name
# of the generated static. CLDR's `en` is American English: `en-US` has no data of its own.
LOCALES = [("en-US", "en", "EN_US"), ("es-US", "es-US", "ES_US")]

NBSP = " "


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    sys.exit(1)


def rust_str(value: str) -> str:
    out = []
    for char in value:
        if char == "\\":
            out.append("\\\\")
        elif char == '"':
            out.append('\\"')
        elif char.isascii() and char.isprintable():
            out.append(char)
        else:
            out.append(f"\\u{{{ord(char):04x}}}")
    return '"' + "".join(out) + '"'


def rust_char(value: str) -> str:
    if len(value) != 1:
        fail(f"expected one character, found {value!r}")
    if value == "'" or value == "\\":
        return f"'\\{value}'"
    if value.isascii() and value.isprintable():
        return f"'{value}'"
    return f"'\\u{{{ord(value):04x}}}'"


def spaced(symbol: str) -> bool:
    """Whether CLDR puts a no-break space between `symbol` and the digits after it.

    Its currency spacing does, after the symbol, when the symbol's last character matches
    `[[:^S:]&[:^Z:]]`: anything but a symbol (such as `$`) or a separator. That covers letters,
    as the `alphaNextToNumber` pattern does, and also punctuation, such as the period of `Cg.`,
    as ICU spaces it.
    """
    category = unicodedata.category(symbol[-1])
    return not (category.startswith("S") or category.startswith("Z"))


def load(tag: str, cldr: str) -> tuple[dict, dict]:
    numbers_doc = json.loads((DATA / cldr / "numbers.json").read_text(encoding="utf-8"))
    currencies_doc = json.loads((DATA / cldr / "currencies.json").read_text(encoding="utf-8"))
    try:
        numbers = numbers_doc["main"][cldr]["numbers"]
        currencies = currencies_doc["main"][cldr]["numbers"]["currencies"]
    except KeyError as missing:
        fail(f"{tag}: CLDR data lacks {missing}")
    if numbers.get("defaultNumberingSystem") != "latn":
        fail(f"{tag}: numbering system {numbers.get('defaultNumberingSystem')!r}, not latn")
    return numbers, currencies


def main() -> None:
    lines = [
        "// @generated by tools/gen_locale_table.py from data/cldr/.",
        "// DO NOT EDIT BY HAND. See data/cldr/README.md for provenance and verification.",
        "// One currency per line; rustfmt skips this file (see `mod table` in locale.rs).",
        "",
        "use super::{LocaleData, Symbol};",
        "",
    ]
    for tag, cldr, name in LOCALES:
        numbers, currencies = load(tag, cldr)
        symbols = numbers["symbols-numberSystem-latn"]
        formats = numbers["currencyFormats-numberSystem-latn"]
        if numbers.get("minimumGroupingDigits") != "1":
            fail(f"{tag}: minimumGroupingDigits {numbers.get('minimumGroupingDigits')!r}, not 1")
        if formats.get("standard") != "¤#,##0.00":
            fail(f"{tag}: currency pattern {formats.get('standard')!r}")
        if formats.get("standard-alphaNextToNumber") != f"¤{NBSP}#,##0.00":
            fail(f"{tag}: alphaNextToNumber pattern {formats.get('standard-alphaNextToNumber')!r}")
        # `afterCurrency` governs a symbol before the digits, which is where `Locale` puts it;
        # `beforeCurrency` one after them. Both must be the rule `spaced` implements.
        expected_spacing = {
            "currencyMatch": "[[:^S:]&[:^Z:]]",
            "surroundingMatch": "[:digit:]",
            "insertBetween": NBSP,
        }
        spacing = formats.get("currencySpacing", {})
        for side in ("afterCurrency", "beforeCurrency"):
            if spacing.get(side) != expected_spacing:
                fail(f"{tag}: currency spacing {side} {spacing.get(side)!r}")
        decimal_pattern = numbers["decimalFormats-numberSystem-latn"].get("standard")
        if decimal_pattern != "#,##0.###":
            fail(f"{tag}: decimal pattern {decimal_pattern!r}")
        decimal, group, minus = symbols["decimal"], symbols["group"], symbols["minusSign"]
        if decimal == group:
            fail(f"{tag}: decimal and group symbols are both {decimal!r}")
        for own in ("currencyDecimal", "currencyGroup"):
            if own in symbols:
                fail(f"{tag}: amounts of money have a separator of their own, {own}")

        entries = []
        for code in sorted(currencies):
            if len(code) != 3 or not code.isascii() or not code.isalpha() or not code.isupper():
                fail(f"{tag}: malformed currency code {code!r}")
            for own in ("decimal", "group", "pattern"):
                if own in currencies[code]:
                    fail(f"{tag}: {code} has a {own} of its own, {currencies[code][own]!r}")
            symbol = currencies[code].get("symbol", code)
            if not symbol or any(unicodedata.category(c).startswith("C") for c in symbol):
                fail(f"{tag}: unusable symbol {symbol!r} for {code}")
            # A symbol that is the code itself is what `Locale` shows without a table entry.
            if symbol != code:
                entries.append((code, symbol, spaced(symbol)))

        lines.append(f"/// {tag}: CLDR's `{cldr}`.")
        lines.append(f"pub(super) static {name}: LocaleData = LocaleData {{")
        lines.append(f"    tag: {rust_str(tag)},")
        lines.append(f"    decimal: {rust_char(decimal)},")
        lines.append(f"    group: {rust_char(group)},")
        lines.append(f"    minus: {rust_char(minus)},")
        lines.append("    symbols: &[")
        for code, symbol, is_spaced in entries:
            lines.append(
                f"        Symbol {{ code: {rust_str(code)}, text: {rust_str(symbol)}, "
                f"spaced: {'true' if is_spaced else 'false'} }},"
            )
        lines.append("    ],")
        lines.append("};")
        lines.append("")
        print(f"{tag}: {len(entries)} currencies with a symbol of their own")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(CRATE)}")


if __name__ == "__main__":
    main()
