#!/usr/bin/env python3
"""Generate src/currency/table.rs from data/iso4217/codes-all.csv.

Run from anywhere:  python3 core/crates/keel-types/tools/gen_currency_table.py

The script validates its input aggressively and exits non-zero on anything unexpected, so a bad
data update can never silently produce a wrong currency table. See data/iso4217/README.md.
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

CRATE = Path(__file__).resolve().parent.parent
CSV_PATH = CRATE / "data" / "iso4217" / "codes-all.csv"
OUT_PATH = CRATE / "src" / "currency" / "table.rs"

# Active ISO 4217 codes that are not spendable currencies.
FUNDS = {"BOV", "CHE", "CHW", "CLF", "COU", "MXV", "USN", "UYI", "UYW"}
UNITS_OF_ACCOUNT = {"XAD", "XDR", "XSU", "XUA"}
BOND_MARKET_UNITS = {"XBA", "XBB", "XBC", "XBD"}
PRECIOUS_METALS = {"XAG", "XAU", "XPD", "XPT"}
TESTING_AND_NONE = {"XTS", "XXX"}
EXCLUDED = FUNDS | UNITS_OF_ACCOUNT | BOND_MARKET_UNITS | PRECIOUS_METALS | TESTING_AND_NONE

# Currencies withdrawn since 2020 that remain importable (historic data), with their minor units.
# Minor units cross-checked against the iso_currency crate v0.7.1 (BGN, CUC, HRK, SLL, ZWL = 2);
# ANG (absent from that crate) had 2 minor units in its last ISO listing, like its successor XCG.
WITHDRAWN_SINCE_2020 = {"ANG": 2, "BGN": 2, "CUC": 2, "HRK": 2, "SLL": 2, "ZWL": 2}


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    sys.exit(1)


def rust_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main() -> None:
    rows = list(csv.DictReader(CSV_PATH.open(encoding="utf-8")))
    expected = ["Entity", "Currency", "AlphabeticCode", "NumericCode", "MinorUnit", "WithdrawalDate"]
    if not rows or list(rows[0].keys()) != expected:
        fail(f"unexpected CSV header: {list(rows[0].keys()) if rows else 'empty file'}")

    active: dict[str, tuple[int, int, str]] = {}
    withdrawn: dict[str, tuple[int, str, str]] = {}  # code -> (numeric, name, "YYYY-MM")

    for row in rows:
        code = row["AlphabeticCode"].strip()
        if not code:
            continue  # entities without a universal currency (e.g. Antarctica)
        if len(code) != 3 or not code.isascii() or not code.isupper() or not code.isalpha():
            fail(f"malformed alphabetic code {code!r}")
        numeric_text = row["NumericCode"].strip()
        name = row["Currency"].strip()
        withdrawal = row["WithdrawalDate"].strip()

        if withdrawal:
            if code not in WITHDRAWN_SINCE_2020:
                continue
            if len(withdrawal) != 7 or withdrawal[4] != "-":
                fail(f"unexpected withdrawal date {withdrawal!r} for {code}")
            if not numeric_text.isdigit():
                fail(f"withdrawn {code} has no numeric code")
            previous = withdrawn.get(code)
            if previous is None or withdrawal > previous[2]:
                withdrawn[code] = (int(numeric_text), name, withdrawal)
            continue

        if code in EXCLUDED:
            continue
        minor_text = row["MinorUnit"].strip()
        if minor_text not in {"0", "2", "3"}:
            fail(f"circulating currency {code} has unexpected minor unit {minor_text!r}")
        if not (numeric_text.isdigit() and len(numeric_text) == 3):
            fail(f"circulating currency {code} has malformed numeric code {numeric_text!r}")
        record = (int(numeric_text), int(minor_text), name)
        if code in active and active[code] != record:
            fail(f"inconsistent rows for {code}: {active[code]} vs {record}")
        active[code] = record

    missing = set(WITHDRAWN_SINCE_2020) - set(withdrawn)
    if missing:
        fail(f"withdrawn currencies not found in CSV: {sorted(missing)}")
    overlap = set(active) & set(withdrawn)
    if overlap:
        fail(f"codes both active and withdrawn: {sorted(overlap)}")

    entries = []
    for code, (numeric, minor, name) in active.items():
        entries.append((code, numeric, minor, name, None))
    for code, (numeric, name, since) in withdrawn.items():
        entries.append((code, numeric, WITHDRAWN_SINCE_2020[code], name, since))
    entries.sort(key=lambda entry: entry[0])

    lines = [
        "// @generated by tools/gen_currency_table.py from data/iso4217/codes-all.csv.",
        "// DO NOT EDIT BY HAND. See data/iso4217/README.md for provenance and verification.",
        "// One currency per line; rustfmt skips this file (see `mod table` in currency.rs).",
        "",
        "use super::{Currency, CurrencyInfo, CurrencyStatus};",
        "",
    ]
    for code, numeric, minor, name, since in entries:
        if since is None:
            status = "CurrencyStatus::Circulating"
        else:
            year, month = since.split("-")
            status = f"CurrencyStatus::Withdrawn {{ year: {int(year)}, month: {int(month)} }}"
        lines.append(
            f"static {code}_INFO: CurrencyInfo = "
            f"CurrencyInfo::new({rust_str(code)}, {numeric}, {minor}, {rust_str(name)}, {status});"
        )
    lines.append("")
    lines.append("/// Every currency in the table, sorted by alphabetic code.")
    lines.append(f"pub(super) static TABLE: [&CurrencyInfo; {len(entries)}] = [")
    for code, *_ in entries:
        lines.append(f"    &{code}_INFO,")
    lines.append("];")
    lines.append("")
    lines.append("impl Currency {")
    for code, numeric, minor, name, since in entries:
        suffix = "" if since is None else f" Withdrawn {since}."
        lines.append(
            f"    /// {name} (`{code}`, ISO 4217 numeric {numeric:03}, {minor} minor units).{suffix}"
        )
        lines.append(f"    pub const {code}: Currency = Currency(&{code}_INFO);")
    lines.append("}")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    circulating = sum(1 for entry in entries if entry[4] is None)
    print(f"wrote {OUT_PATH.relative_to(CRATE)}: {circulating} circulating + "
          f"{len(entries) - circulating} withdrawn currencies")


if __name__ == "__main__":
    main()
