// @generated by tools/gen_locale_table.py from data/cldr/.
// DO NOT EDIT BY HAND. See data/cldr/README.md for provenance and verification.
// One currency per line; rustfmt skips this file (see `mod table` in locale.rs).

use super::{LocaleData, Symbol};

/// en-US: CLDR's `en`.
pub(super) static EN_US: LocaleData = LocaleData {
    tag: "en-US",
    decimal: '.',
    group: ',',
    minus: '-',
    symbols: &[
        Symbol { code: "AUD", text: "A$", spaced: false },
        Symbol { code: "BRL", text: "R$", spaced: false },
        Symbol { code: "CAD", text: "CA$", spaced: false },
        Symbol { code: "CNY", text: "CN\u{00a5}", spaced: false },
        Symbol { code: "EUR", text: "\u{20ac}", spaced: false },
        Symbol { code: "GBP", text: "\u{00a3}", spaced: false },
        Symbol { code: "HKD", text: "HK$", spaced: false },
        Symbol { code: "ILS", text: "\u{20aa}", spaced: false },
        Symbol { code: "INR", text: "\u{20b9}", spaced: false },
        Symbol { code: "JPY", text: "\u{00a5}", spaced: false },
        Symbol { code: "KRW", text: "\u{20a9}", spaced: false },
        Symbol { code: "MXN", text: "MX$", spaced: false },
        Symbol { code: "NZD", text: "NZ$", spaced: false },
        Symbol { code: "PHP", text: "\u{20b1}", spaced: false },
        Symbol { code: "TWD", text: "NT$", spaced: false },
        Symbol { code: "USD", text: "$", spaced: false },
        Symbol { code: "VND", text: "\u{20ab}", spaced: false },
        Symbol { code: "XAF", text: "FCFA", spaced: true },
        Symbol { code: "XCD", text: "EC$", spaced: false },
        Symbol { code: "XCG", text: "Cg.", spaced: true },
        Symbol { code: "XOF", text: "F\u{202f}CFA", spaced: true },
        Symbol { code: "XPF", text: "CFPF", spaced: true },
        Symbol { code: "XXX", text: "\u{00a4}", spaced: false },
    ],
};

/// es-US: CLDR's `es-US`.
pub(super) static ES_US: LocaleData = LocaleData {
    tag: "es-US",
    decimal: '.',
    group: ',',
    minus: '-',
    symbols: &[
        Symbol { code: "ESP", text: "\u{20a7}", spaced: false },
        Symbol { code: "JPY", text: "\u{00a5}", spaced: false },
        Symbol { code: "USD", text: "$", spaced: false },
        Symbol { code: "XCG", text: "Cg.", spaced: true },
        Symbol { code: "XPF", text: "CFPF", spaced: true },
        Symbol { code: "XXX", text: "\u{00a4}", spaced: false },
    ],
};
